// Offline --selftest: parser and framing only, never opens HID.
static int selftest(void) {
  struct device_state state = {
    .left = -1, .right = -1, .case_level = -1, .left_missing = 0,
    .right_missing = 0, .mode = -1, .lighting = -1, .call_context = true, .tap_seq = 0,
  };
  const unsigned char battery[] = {0xcc, 0x12, 0x07, 0, 0, 5, 91, 98, 100};
  const unsigned char mode[] = {0xcc, 0x12, 0x25, 0, 0, 2};
  const unsigned char anc_lvl[] = {0xcc, 0x12, 0x2b, 0, 0, 2};
  const unsigned char anc_adp[] = {0xcc, 0x12, 0x2c, 0, 0, 1};
  const unsigned char prompt[] = {0xcc, 0x12, 0x28, 0, 0, 1};
  apply_packet(NULL, &state, battery, sizeof(battery));
  apply_packet(NULL, &state, mode, sizeof(mode));
  apply_packet(NULL, &state, anc_lvl, sizeof(anc_lvl));
  apply_packet(NULL, &state, anc_adp, sizeof(anc_adp));
  apply_packet(NULL, &state, prompt, sizeof(prompt));
  if (!state.receiver || !state.connected) return 1;
  if (state.left != 91 || state.right != 98 || state.case_level != 100) return 1;
  if (state.mode != 2 || state.anc_level != 2 || !state.anc_adaptive || state.voice_prompt != 1) return 1;
  const unsigned char left_tap[] = {204, 112, 0, 0, 0, 0x00, 0x01, 0};
  apply_packet(NULL, &state, left_tap, sizeof(left_tap));
  if (state.tap_seq != 0) return 1;
  const unsigned char left_double[] = {204, 112, 0, 0, 0, 0x00, 0x02, 0};
  apply_packet(NULL, &state, left_double, sizeof(left_double));
  if (state.tap_seq != 0) return 1;
  state.call_context = false;
  const unsigned char right_tap[] = {204, 112, 0, 0, 0, 0x01, 0x01, 0};
  apply_packet(NULL, &state, right_tap, sizeof(right_tap));
  if (state.tap_seq != 0) return 1;
  state.call_context = true;
  apply_packet(NULL, &state, right_tap, sizeof(right_tap));
  if (state.tap_seq != 1) return 1;
  apply_packet(NULL, &state, right_tap, sizeof(right_tap));
  if (state.tap_seq != 2) return 1;
  const unsigned char right_double[] = {204, 112, 0, 0, 0, 0x01, 0x02, 0};
  apply_packet(NULL, &state, right_double, sizeof(right_double));
  if (state.tap_seq != 2) return 1;
  const unsigned char short_tap[] = {204, 112, 0, 0, 0, 1, 1};
  apply_packet(NULL, &state, short_tap, sizeof(short_tap));
  if (state.tap_seq != 3) return 1;
  state.tap_seq = INT_MAX;
  apply_packet(NULL, &state, short_tap, sizeof(short_tap));
  if (state.tap_seq != INT_MAX) return 1;
  const unsigned char in_case[] = {0xcc, 0x12, 0x07, 0, 0, 0, 255, 255, 100};
  for (int i = 0; i < 6; i++) apply_packet(NULL, &state, in_case, sizeof(in_case));
  if (state.connected) return 1;
  char json[STATUS_BUFFER_SIZE];
  reset_receiver_state(&state);
  format_state(json, sizeof(json), &state);
  if (!strstr(json, "\"microphone_state\":\"unknown\"")) return 1;
  struct device_state before = state;
  struct command_source ignored = {.fd = -1};
  const char obsolete[] = "mic_state muted\nmic_state live\n";
  if (!consume_commands(NULL, &state, &ignored, obsolete, sizeof(obsolete) - 1)) return 1;
  char after[STATUS_BUFFER_SIZE];
  format_state(after, sizeof(after), &state);
  if (strcmp(json, after) != 0 || state.tap_seq != before.tap_seq) return 1;
  struct command_source owner_source = {.fd = STDIN_FILENO};
  struct command_source clients[MAX_CLIENTS];
  for (int i = 0; i < MAX_CLIENTS; i++) clients[i] = (struct command_source){.fd = -1};
  if (!consume_commands(NULL, &state, &owner_source, "ca", 2)) return 1;
  if (!consume_commands(NULL, &state, &owner_source, "ll on\n", 6)) return 1;
  clients[0] = (struct command_source){.fd = 42, .call_requested = true};
  if (!aggregate_call_requested(&owner_source, clients)) return 1;
  if (!consume_commands(NULL, &state, &owner_source, "call off\n", 9)) return 1;
  if (!aggregate_call_requested(&owner_source, clients)) return 1;
  clients[0].call_requested = false;
  if (aggregate_call_requested(&owner_source, clients)) return 1;
  puts("ok");
  return 0;
}
